"""Emit src/PatchTable.g.h from the per-runtime patch JSON."""

from __future__ import annotations

import argparse
import json

CATS = [
    "index_mask",
    "age_mask",
    "age_inc_or_count",
    "table_bytes",
    "clear_age",
    "clear_next",
    "init_guard",
]

HEADER = """// GENERATED by probes/gen_cpp.py -- do not edit by hand.
//
// One entry per instruction field that must change when Skyrim's reference
// handle index widens from 20 to 21 bits. Every rewrite is the same length as
// the instruction it replaces, so patching is an in-place byte edit.
//
// `orig` holds the complete stock instruction bytes. The plugin refuses to
// patch anything whose bytes do not match, which is what makes applying the
// wrong runtime's table impossible rather than merely unlikely.
#pragma once

#include <cstdint>

namespace shcr
{
    enum Category : uint8_t
    {
%s
    };

    inline const char* CategoryName(uint8_t c)
    {
        static const char* kNames[] = {
%s
        };
        return c < (sizeof(kNames) / sizeof(kNames[0])) ? kNames[c] : "?";
    }

    struct FieldPatch
    {
        uint32_t rva;       // instruction RVA
        uint8_t  len;       // instruction length
        uint8_t  fieldOff;  // byte offset of the field inside the instruction
        uint8_t  fieldW;    // 1 or 4
        uint8_t  cat;       // Category
        uint32_t oldVal;
        uint32_t newVal;
        uint8_t  orig[15];  // stock instruction bytes (len valid)
    };

    struct BytePatch
    {
        uint32_t rva;       // first byte of one or more whole instructions
        uint8_t  len;       // same for orig and repl, at most 15
        uint8_t  cat;       // Category
        uint8_t  orig[15];  // exact stock bytes (len valid)
        uint8_t  repl[15];  // exact replacement bytes (len valid)
    };

    struct TableRef
    {
        uint32_t rva;       // instruction RVA, not a bare disp32 RVA
        uint8_t  len;       // complete stock instruction length
        uint8_t  dispOff;   // disp32 byte offset inside the instruction
        uint8_t  orig[15];  // complete stock instruction bytes (len valid)
    };

    struct ExactSite
    {
        uint32_t rva;
        uint8_t  len;
        uint8_t  orig[15];
    };

    struct AssignmentHookSite
    {
        uint32_t callRva;         // address of the stock five-byte rel32 CALL
        uint32_t functionRva;     // entry of the .pdata owner containing this CALL
        uint8_t  callBytes[5];    // exact stock CALL, including its displacement
        uint8_t  setupBytes[11];  // exact bytes at [callRva-11, callRva)
        uint8_t  functionBytes[16]; // exact owner-entry fingerprint
    };

    enum PlayerObjectRegister : uint8_t
    {
        kPlayerObject_RBX = 3,
        kPlayerObject_RDI = 7,
    };

    struct PlayerSelectorHookSite
    {
        uint32_t hookRva;           // stock six-byte MOV EAX,[free-head]
        uint32_t functionRva;       // exact allocator-clone owner
        uint32_t objectSetupRva;    // MOV nonvolatile-candidate,RDX
        uint32_t lockCallRva;       // manager write-lock call
        uint32_t unlockCallRva;     // matching manager unlock call
        uint8_t  objectRegister;    // PlayerObjectRegister
        uint8_t  hookBytes[6];
        uint8_t  functionBytes[16];
        uint8_t  objectSetupBytes[3];
        uint8_t  lockCallBytes[5];
        uint8_t  unlockCallBytes[5];
        uint16_t stackAllocation;
        uint16_t preHookLen;
        uint32_t preHookRva;
        uint8_t  preHookBytes[256];
        uint16_t continuationLen;
        uint32_t continuationRva;
        uint8_t  continuationBytes[256];
    };

    struct PlayerReleaseHookSite
    {
        uint32_t hookRva;           // stock six-byte MOV EAX,[free-tail]
        uint32_t resumeRva;         // ordinary FIFO continuation
        uint32_t reservedExitRva;   // manager-unlock path, FIFO untouched
        uint32_t functionRva;       // canonical release owner
        uint32_t unlockCallRva;
        uint8_t  hookBytes[6];
        uint8_t  functionBytes[16];
        uint8_t  unlockCallBytes[5];
        uint16_t preHookLen;
        uint32_t preHookRva;
        uint8_t  preHookBytes[256];
        uint16_t continuationLen;
        uint32_t continuationRva;
        uint8_t  continuationBytes[128];
    };

    struct PlayerLifecycleMetadata
    {
        uint32_t creationFunctionRva;
        uint8_t  creationFunctionBytes[16];
        uint32_t constructorFunctionRva;
        uint8_t  constructorFunctionBytes[16];
        ExactSite constructorCall;
        uint16_t constructorPreHookLen;
        uint32_t constructorPreHookRva;
        uint8_t  constructorPreHookBytes[256];
        uint16_t constructorPostCallLen;
        uint32_t constructorPostCallRva;
        uint8_t  constructorPostCallBytes[64];
        ExactSite singletonStore;
        ExactSite candidateLoad;
        ExactSite allocatorCall;
        ExactSite handleStore;
        ExactSite formIDSetup;
        ExactSite formIDCall;
        uint32_t teardownFunctionRva;
        uint8_t  teardownFunctionBytes[16];
        ExactSite teardownHandleLoad;
        ExactSite teardownReleaseCall;
        const ExactSite* teardownZeroSources;
        uint32_t teardownZeroSourceCount;
        ExactSite singletonClear;
    };

    struct Profile
    {
        const char*       name;
        uint32_t          runtimeVersion;  // (major<<24)|(minor<<16)|(build<<4)|sub
        uint32_t          tableRva;
        uint32_t          headRva;
        uint32_t          tailRva;
        uint32_t          lockRva;
        uint32_t          lockWriteRva;
        uint32_t          unlockWriteRva;
        uint32_t          stockEntries;
        uint32_t          raisedEntries;
        uint32_t          entrySize;
        uint32_t          assignmentHelperRva;
        uint8_t           assignmentHelperBytes[16];
        const AssignmentHookSite* assignmentHookSites;
        uint32_t          assignmentHookSiteCount;
        uint32_t          playerSingletonRva;
        uint32_t          playerHandleRva;
        const PlayerSelectorHookSite* playerSelectorHookSites;
        uint32_t          playerSelectorHookSiteCount;
        PlayerReleaseHookSite playerReleaseHook;
        PlayerLifecycleMetadata playerLifecycle;
        const FieldPatch* fields;
        uint32_t          fieldCount;
        const TableRef*   tableRefs;
        uint32_t          tableRefCount;
        const BytePatch*  initPatches;  // applied only when the runtime is pristine/pre-init
        uint32_t          initPatchCount;
    };
"""


def pack_version(major: int, minor: int, build: int, sub: int) -> int:
    return ((major & 0xFF) << 24) | ((minor & 0xFF) << 16) | ((build & 0xFFF) << 4) | (sub & 0xF)


RUNTIMES = (
    ("SE", "Skyrim SE", (1, 5, 97, 0)),
    ("AE", "Skyrim AE", (1, 6, 1170, 0)),
    ("GOG", "Skyrim GOG", (1, 6, 1179, 0)),
    ("VR", "Skyrim VR", (1, 4, 15, 0)),
)


def emit(runtime: str, label: str, data: dict,
         version: tuple[int, int, int, int]) -> str:
    tag = runtime
    out = []
    out.append(f"    // ---- {tag}: {label} {'.'.join(map(str, version))} "
               f"({len(data['patches'])} field rewrites, "
               f"{len(data['table_refs'])} table references)")
    out.append(f"    inline const FieldPatch k{tag}Fields[] = {{")
    for p in data["patches"]:
        raw = bytes.fromhex(p["orig"])[:15]
        b = ", ".join(f"0x{x:02x}" for x in raw)
        out.append(
            f"        {{ 0x{p['rva']:08x}, {p['len']}, {p['field_off']}, {p['field_w']}, "
            f"{CATS.index(p['cat'])}, 0x{p['old']:08x}, 0x{p['new']:08x}, {{ {b} }} }},"
            f"  // {p['asm']}"
        )
    out.append("    };")

    out.append(f"    inline const TableRef k{tag}TableRefs[] = {{")
    for p in data["table_refs"]:
        raw = bytes.fromhex(p["orig"])[:15]
        b = ", ".join(f"0x{x:02x}" for x in raw)
        out.append(
            f"        {{ 0x{p['rva']:08x}, {p['len']}, {p['disp_off']}, {{ {b} }} }},"
            f"  // {p['asm']}"
        )
    out.append("    };")

    out.append(f"    inline const BytePatch k{tag}InitPatches[] = {{")
    for p in data["init_patches"]:
        orig = bytes.fromhex(p["orig"])[:15]
        repl = bytes.fromhex(p["new"])[:15]
        ob = ", ".join(f"0x{x:02x}" for x in orig)
        nb = ", ".join(f"0x{x:02x}" for x in repl)
        out.append(
            f"        {{ 0x{p['rva']:08x}, {p['len']}, {CATS.index(p['cat'])}, "
            f"{{ {ob} }}, {{ {nb} }} }},  // {p['asm']}"
        )
    out.append("    };")

    hooks = data["assignment_hooks"]
    helper = bytes.fromhex(hooks["helper_bytes"])
    if len(helper) != 16:
        raise ValueError(f"{tag} assignment helper fingerprint is not 16 bytes")
    out.append(f"    inline const AssignmentHookSite k{tag}AssignmentHookSites[] = {{")
    for p in hooks["sites"]:
        call = bytes.fromhex(p["call_bytes"])
        setup = bytes.fromhex(p["setup_bytes"])
        function = bytes.fromhex(p["function_bytes"])
        if len(call) != 5 or len(setup) != 11 or len(function) != 16 or \
                p["setup_rva"] != p["call_rva"] - 11:
            raise ValueError(f"{tag} assignment hook at {p['call_rva']:#x} has invalid widths")
        cb = ", ".join(f"0x{x:02x}" for x in call)
        sb = ", ".join(f"0x{x:02x}" for x in setup)
        fb = ", ".join(f"0x{x:02x}" for x in function)
        out.append(
            f"        {{ 0x{p['call_rva']:08x}, 0x{p['function_rva']:08x}, "
            f"{{ {cb} }}, {{ {sb} }}, {{ {fb} }} }},"
            f"  // owner 0x{p['function_rva']:08x}, writer 0x{p['writer_rva']:08x}"
        )
    out.append("    };")
    hb = ", ".join(f"0x{x:02x}" for x in helper)

    reservation = data["player_reservation"]
    selectors = reservation["selectors"]
    out.append(f"    inline const PlayerSelectorHookSite k{tag}PlayerSelectorHookSites[] = {{")
    register_numbers = {"rbx": 3, "rdi": 7}
    for p in selectors:
        hook = bytes.fromhex(p["hook_bytes"])
        function = bytes.fromhex(p["function_bytes"])
        object_setup = bytes.fromhex(p["object_setup_bytes"])
        lock_call = bytes.fromhex(p["lock_call_bytes"])
        unlock_call = bytes.fromhex(p["unlock_call_bytes"])
        pre_hook = bytes.fromhex(p["pre_hook_bytes"])
        continuation = bytes.fromhex(p["continuation_bytes"])
        if len(hook) != 6 or len(function) != 16 or len(object_setup) != 3 or \
                len(lock_call) != 5 or len(unlock_call) != 5 or \
                not (0 < len(pre_hook) <= 256) or \
                p["pre_hook_rva"] != p["function_rva"] or \
                p["pre_hook_rva"] + len(pre_hook) != p["hook_rva"] or \
                not (0 < len(continuation) <= 256) or \
                p["continuation_rva"] != p["hook_rva"] + 6 or \
                int(p["stack_allocation"]) < 0x20 or \
                p["object_register"] not in register_numbers:
            raise ValueError(f"{tag} player selector at {p['hook_rva']:#x} has invalid widths")
        fmt = lambda raw: ", ".join(f"0x{x:02x}" for x in raw)
        out.append(
            f"        {{ 0x{p['hook_rva']:08x}, 0x{p['function_rva']:08x}, "
            f"0x{p['object_setup_rva']:08x}, 0x{p['lock_call_rva']:08x}, "
            f"0x{p['unlock_call_rva']:08x}, {register_numbers[p['object_register']]}, "
            f"{{ {fmt(hook)} }}, {{ {fmt(function)} }}, "
            f"{{ {fmt(object_setup)} }}, {{ {fmt(lock_call)} }}, "
            f"{{ {fmt(unlock_call)} }}, 0x{int(p['stack_allocation']):x}, "
            f"{len(pre_hook)}, 0x{p['pre_hook_rva']:08x}, "
            f"{{ {fmt(pre_hook)} }}, "
            f"{len(continuation)}, 0x{p['continuation_rva']:08x}, "
            f"{{ {fmt(continuation)} }} }},"
            f"  // candidate in {p['object_register'].upper()}"
        )
    out.append("    };")

    release = reservation["release"]
    release_hook = bytes.fromhex(release["hook_bytes"])
    release_function = bytes.fromhex(release["function_bytes"])
    release_unlock = bytes.fromhex(release["unlock_call_bytes"])
    release_pre_hook = bytes.fromhex(release["pre_hook_bytes"])
    release_continuation = bytes.fromhex(release["continuation_bytes"])
    if len(release_hook) != 6 or len(release_function) != 16 or \
            len(release_unlock) != 5 or \
            not (0 < len(release_pre_hook) <= 256) or \
            release["pre_hook_rva"] != release["function_rva"] or \
            release["pre_hook_rva"] + len(release_pre_hook) != \
                release["hook_rva"] or \
            not (0 < len(release_continuation) <= 128) or \
            release["continuation_rva"] != release["resume_rva"]:
        raise ValueError(f"{tag} player release hook has invalid widths")
    fmt = lambda raw: ", ".join(f"0x{x:02x}" for x in raw)
    release_cpp = (
        f"{{ 0x{release['hook_rva']:08x}, 0x{release['resume_rva']:08x}, "
        f"0x{release['reserved_exit_rva']:08x}, 0x{release['function_rva']:08x}, "
        f"0x{release['unlock_call_rva']:08x}, {{ {fmt(release_hook)} }}, "
        f"{{ {fmt(release_function)} }}, {{ {fmt(release_unlock)} }}, "
        f"{len(release_pre_hook)}, 0x{release['pre_hook_rva']:08x}, "
        f"{{ {fmt(release_pre_hook)} }}, "
        f"{len(release_continuation)}, 0x{release['continuation_rva']:08x}, "
        f"{{ {fmt(release_continuation)} }} }}")

    lifecycle = reservation["lifecycle"]
    creation = lifecycle["creation"]
    teardown = lifecycle["teardown"]

    def exact_site_cpp(record: dict) -> str:
        raw = bytes.fromhex(record["bytes"])
        if not (0 < len(raw) <= 15):
            raise ValueError(
                f"{tag} lifecycle site {record['rva']:#x} has invalid width")
        return (f"{{ 0x{record['rva']:08x}, {len(raw)}, "
                f"{{ {fmt(raw)} }} }}")

    creation_function = bytes.fromhex(creation["function_bytes"])
    constructor_function = bytes.fromhex(creation["constructor_function_bytes"])
    constructor_pre_hook = bytes.fromhex(creation["constructor_pre_hook_bytes"])
    constructor_post_call = bytes.fromhex(
        creation["constructor_post_call_bytes"])
    teardown_function = bytes.fromhex(teardown["function_bytes"])
    if len(creation_function) != 16 or len(constructor_function) != 16 or \
            len(teardown_function) != 16:
        raise ValueError(f"{tag} player lifecycle owner fingerprint is not 16 bytes")
    if not (0 < len(constructor_pre_hook) <= 256) or \
            creation["constructor_pre_hook_rva"] != creation["function_rva"] or \
            creation["constructor_pre_hook_rva"] + len(constructor_pre_hook) != \
                creation["constructor_call"]["rva"]:
        raise ValueError(f"{tag} player constructor pre-hook window is invalid")
    if not (0 < len(constructor_post_call) <= 64) or \
            creation["constructor_post_call_rva"] != \
                creation["constructor_call"]["rva"] + \
                len(bytes.fromhex(creation["constructor_call"]["bytes"])) or \
            creation["constructor_post_call_rva"] + len(constructor_post_call) != \
                creation["singleton_store"]["rva"]:
        raise ValueError(
            f"{tag} player constructor post-call publication window is invalid")
    out.append(f"    inline const ExactSite k{tag}PlayerTeardownZeroSources[] = {{")
    for record in teardown["zero_sources"]:
        out.append(f"        {exact_site_cpp(record)},")
    out.append("    };")
    lifecycle_cpp = (
        f"{{ 0x{creation['function_rva']:08x}, {{ {fmt(creation_function)} }}, "
        f"0x{creation['constructor_function_rva']:08x}, "
        f"{{ {fmt(constructor_function)} }}, "
        f"{exact_site_cpp(creation['constructor_call'])}, "
        f"{len(constructor_pre_hook)}, "
        f"0x{creation['constructor_pre_hook_rva']:08x}, "
        f"{{ {fmt(constructor_pre_hook)} }}, "
        f"{len(constructor_post_call)}, "
        f"0x{creation['constructor_post_call_rva']:08x}, "
        f"{{ {fmt(constructor_post_call)} }}, "
        f"{exact_site_cpp(creation['singleton_store'])}, "
        f"{exact_site_cpp(creation['candidate_load'])}, "
        f"{exact_site_cpp(creation['allocator_call'])}, "
        f"{exact_site_cpp(creation['handle_store'])}, "
        f"{exact_site_cpp(creation['formid_setup'])}, "
        f"{exact_site_cpp(creation['formid_call'])}, "
        f"0x{teardown['function_rva']:08x}, {{ {fmt(teardown_function)} }}, "
        f"{exact_site_cpp(teardown['handle_load'])}, "
        f"{exact_site_cpp(teardown['release_call'])}, "
        f"k{tag}PlayerTeardownZeroSources, "
        f"static_cast<uint32_t>(sizeof(k{tag}PlayerTeardownZeroSources) / "
        f"sizeof(k{tag}PlayerTeardownZeroSources[0])), "
        f"{exact_site_cpp(teardown['singleton_clear'])} }}")

    out.append(f"""    inline const Profile k{tag}Profile = {{
        "{label} {'.'.join(map(str, version))}",
        0x{pack_version(*version):08x}u,
        0x{data['table_rva']:08x}u, 0x{data['head_rva']:08x}u, 0x{data['tail_rva']:08x}u, 0x{data['lock_rva']:08x}u,
        0x{data['lock_write_rva']:08x}u, 0x{data['unlock_write_rva']:08x}u,
        0x{data['stock_entries']:x}u, 0x{data['raised_entries']:x}u, 0x{data['entry_size']:x}u,
        0x{hooks['helper_rva']:08x}u, {{ {hb} }},
        k{tag}AssignmentHookSites, static_cast<uint32_t>(sizeof(k{tag}AssignmentHookSites) / sizeof(k{tag}AssignmentHookSites[0])),
        0x{reservation['singleton_rva']:08x}u, 0x{reservation['handle_rva']:08x}u,
        k{tag}PlayerSelectorHookSites, static_cast<uint32_t>(sizeof(k{tag}PlayerSelectorHookSites) / sizeof(k{tag}PlayerSelectorHookSites[0])),
        {release_cpp},
        {lifecycle_cpp},
        k{tag}Fields, static_cast<uint32_t>(sizeof(k{tag}Fields) / sizeof(k{tag}Fields[0])),
        k{tag}TableRefs, static_cast<uint32_t>(sizeof(k{tag}TableRefs) / sizeof(k{tag}TableRefs[0])),
        k{tag}InitPatches, static_cast<uint32_t>(sizeof(k{tag}InitPatches) / sizeof(k{tag}InitPatches[0])),
    }};""")
    return "\n".join(out)


def render(data: dict[str, dict]) -> str:
    enum_body = "\n".join(f"        kCat_{c} = {i}," for i, c in enumerate(CATS))
    names = "\n".join(f'            "{c}",' for c in CATS)

    parts = [HEADER % (enum_body, names)]
    for tag, label, version in RUNTIMES:
        parts.append(emit(tag, label, data[tag], version))
        parts.append("")
    profile_refs = ", ".join(f"&k{tag}Profile" for tag, _, _ in RUNTIMES)
    parts.append(f"""    inline const Profile* const kProfiles[] = {{ {profile_refs} }};
    inline constexpr uint32_t kProfileCount = sizeof(kProfiles) / sizeof(kProfiles[0]);
}}
""")
    return "\n".join(parts)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--se", required=True)
    ap.add_argument("--ae", required=True)
    ap.add_argument("--gog", required=True)
    ap.add_argument("--vr", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    data = {
        "SE": json.load(open(a.se)),
        "AE": json.load(open(a.ae)),
        "GOG": json.load(open(a.gog)),
        "VR": json.load(open(a.vr)),
    }
    missing = [tag for tag, _, _ in RUNTIMES
               if "player_reservation" not in data[tag]]
    if missing:
        raise ValueError(
            "profiles lack generated player-reservation metadata: " + ", ".join(missing))
    text = render(data)
    with open(a.out, "w", newline="\n") as fh:
        fh.write(text)
    counts = ", ".join(
        f"{tag} {len(data[tag]['patches'])}+{len(data[tag]['table_refs'])}"
        for tag, _, _ in RUNTIMES)
    print(f"wrote {a.out}: {counts}")


if __name__ == "__main__":
    main()
