"""Emit src/PatchTable.g.h from the per-runtime patch JSON."""

from __future__ import annotations

import argparse
import json

CATS = [
    "index_mask",
    "age_mask",
    "age_inc_or_count",
    "table_bytes",
    "clear_age",
    "clear_next",
    "clear_inuse",
    "inuse_bit",
    "inuse_bitpos",
    "sidecar_read",
    "sidecar_write",
    "sidecar_release",
    "init_guard",
]

HEADER = """// GENERATED by probes/gen_cpp.py -- do not edit by hand.
//
// One entry per instruction field that must change when Skyrim's reference
// handle index widens from 20 to 22 bits. Every rewrite is the same length as
// the instruction it replaces, so patching is an in-place byte edit.
//
// `orig` holds the complete stock instruction bytes. The plugin refuses to
// patch anything whose bytes do not match, which is what makes applying the
// wrong runtime's table impossible rather than merely unlikely.
#pragma once

#include <cstdint>

namespace shcr
{
    enum Category : uint8_t
    {
%s
    };

    inline const char* CategoryName(uint8_t c)
    {
        static const char* kNames[] = {
%s
        };
        return c < (sizeof(kNames) / sizeof(kNames[0])) ? kNames[c] : "?";
    }

    struct FieldPatch
    {
        uint32_t rva;       // instruction RVA
        uint8_t  len;       // instruction length
        uint8_t  fieldOff;  // byte offset of the field inside the instruction
        uint8_t  fieldW;    // 1 or 4
        uint8_t  cat;       // Category
        uint32_t oldVal;
        uint32_t newVal;
        uint8_t  orig[15];  // stock instruction bytes (len valid)
    };

    struct BytePatch
    {
        uint32_t rva;       // first byte of one or more whole instructions
        uint8_t  len;       // same for orig and repl, at most 15
        uint8_t  cat;       // Category
        uint8_t  orig[15];  // exact stock bytes (len valid)
        uint8_t  repl[15];  // exact replacement bytes (len valid)
    };

    struct TableRef
    {
        uint32_t rva;       // instruction RVA, not a bare disp32 RVA
        uint8_t  len;       // complete stock instruction length
        uint8_t  dispOff;   // disp32 byte offset inside the instruction
        uint8_t  orig[15];  // complete stock instruction bytes (len valid)
    };

    struct ExactSite
    {
        uint32_t rva;
        uint8_t  len;
        uint8_t  orig[15];
    };

    struct AssignmentHookSite
    {
        uint32_t callRva;         // address of the stock five-byte rel32 CALL
        uint32_t functionRva;     // entry of the .pdata owner containing this CALL
        uint8_t  callBytes[5];    // exact stock CALL, including its displacement
        uint8_t  setupBytes[11];  // exact bytes at [callRva-11, callRva)
        uint8_t  functionBytes[16]; // exact owner-entry fingerprint
    };

    struct Profile
    {
        const char*       name;
        uint32_t          runtimeVersion;  // (major<<24)|(minor<<16)|(build<<4)|sub
        uint32_t          tableRva;
        uint32_t          headRva;
        uint32_t          tailRva;
        uint32_t          lockRva;
        uint32_t          lockWriteRva;
        uint32_t          unlockWriteRva;
        uint32_t          stockEntries;
        uint32_t          raisedEntries;
        uint32_t          entrySize;
        uint32_t          assignmentHelperRva;
        uint8_t           assignmentHelperBytes[16];
        const AssignmentHookSite* assignmentHookSites;
        uint32_t          assignmentHookSiteCount;
        const FieldPatch* fields;
        uint32_t          fieldCount;
        const BytePatch*  bytePatches;
        uint32_t          bytePatchCount;
        const TableRef*   tableRefs;
        uint32_t          tableRefCount;
        const BytePatch*  initPatches;  // applied only when the runtime is pristine/pre-init
        uint32_t          initPatchCount;
        const ExactSite*  releaseSites;  // stock clear instructions covered by bytePatches
        uint32_t          releaseSiteCount;
    };
"""


def pack_version(major: int, minor: int, build: int, sub: int) -> int:
    return ((major & 0xFF) << 24) | ((minor & 0xFF) << 16) | ((build & 0xFFF) << 4) | (sub & 0xF)


RUNTIMES = (
    ("SE", "Skyrim SE", (1, 5, 97, 0)),
    ("AE", "Skyrim AE", (1, 6, 1170, 0)),
    ("GOG", "Skyrim GOG", (1, 6, 1179, 0)),
    ("VR", "Skyrim VR", (1, 4, 15, 0)),
)


def emit(runtime: str, label: str, data: dict,
         version: tuple[int, int, int, int]) -> str:
    tag = runtime
    out = []
    out.append(f"    // ---- {tag}: {label} {'.'.join(map(str, version))} "
               f"({len(data['patches'])} field rewrites, {len(data['raw_patches'])} byte rewrites, "
               f"{len(data['table_refs'])} table references)")
    out.append(f"    inline const FieldPatch k{tag}Fields[] = {{")
    for p in data["patches"]:
        raw = bytes.fromhex(p["orig"])[:15]
        b = ", ".join(f"0x{x:02x}" for x in raw)
        out.append(
            f"        {{ 0x{p['rva']:08x}, {p['len']}, {p['field_off']}, {p['field_w']}, "
            f"{CATS.index(p['cat'])}, 0x{p['old']:08x}, 0x{p['new']:08x}, {{ {b} }} }},"
            f"  // {p['asm']}"
        )
    out.append("    };")

    out.append(f"    inline const BytePatch k{tag}BytePatches[] = {{")
    for p in data["raw_patches"]:
        orig = bytes.fromhex(p["orig"])[:15]
        repl = bytes.fromhex(p["new"])[:15]
        ob = ", ".join(f"0x{x:02x}" for x in orig)
        nb = ", ".join(f"0x{x:02x}" for x in repl)
        out.append(
            f"        {{ 0x{p['rva']:08x}, {p['len']}, {CATS.index(p['cat'])}, "
            f"{{ {ob} }}, {{ {nb} }} }},  // {p['asm']}"
        )
    out.append("    };")

    out.append(f"    inline const TableRef k{tag}TableRefs[] = {{")
    for p in data["table_refs"]:
        raw = bytes.fromhex(p["orig"])[:15]
        b = ", ".join(f"0x{x:02x}" for x in raw)
        out.append(
            f"        {{ 0x{p['rva']:08x}, {p['len']}, {p['disp_off']}, {{ {b} }} }},"
            f"  // {p['asm']}"
        )
    out.append("    };")

    out.append(f"    inline const BytePatch k{tag}InitPatches[] = {{")
    for p in data["init_patches"]:
        orig = bytes.fromhex(p["orig"])[:15]
        repl = bytes.fromhex(p["new"])[:15]
        ob = ", ".join(f"0x{x:02x}" for x in orig)
        nb = ", ".join(f"0x{x:02x}" for x in repl)
        out.append(
            f"        {{ 0x{p['rva']:08x}, {p['len']}, {CATS.index(p['cat'])}, "
            f"{{ {ob} }}, {{ {nb} }} }},  // {p['asm']}"
        )
    out.append("    };")

    out.append(f"    inline const ExactSite k{tag}ReleaseSites[] = {{")
    for p in data["release_sites"]:
        raw = bytes.fromhex(p["orig"])[:15]
        b = ", ".join(f"0x{x:02x}" for x in raw)
        out.append(f"        {{ 0x{p['rva']:08x}, {p['len']}, {{ {b} }} }},  // {p['asm']}")
    out.append("    };")

    hooks = data["assignment_hooks"]
    helper = bytes.fromhex(hooks["helper_bytes"])
    if len(helper) != 16:
        raise ValueError(f"{tag} assignment helper fingerprint is not 16 bytes")
    out.append(f"    inline const AssignmentHookSite k{tag}AssignmentHookSites[] = {{")
    for p in hooks["sites"]:
        call = bytes.fromhex(p["call_bytes"])
        setup = bytes.fromhex(p["setup_bytes"])
        function = bytes.fromhex(p["function_bytes"])
        if len(call) != 5 or len(setup) != 11 or len(function) != 16 or \
                p["setup_rva"] != p["call_rva"] - 11:
            raise ValueError(f"{tag} assignment hook at {p['call_rva']:#x} has invalid widths")
        cb = ", ".join(f"0x{x:02x}" for x in call)
        sb = ", ".join(f"0x{x:02x}" for x in setup)
        fb = ", ".join(f"0x{x:02x}" for x in function)
        out.append(
            f"        {{ 0x{p['call_rva']:08x}, 0x{p['function_rva']:08x}, "
            f"{{ {cb} }}, {{ {sb} }}, {{ {fb} }} }},"
            f"  // owner 0x{p['function_rva']:08x}, writer 0x{p['writer_rva']:08x}"
        )
    out.append("    };")
    hb = ", ".join(f"0x{x:02x}" for x in helper)

    out.append(f"""    inline const Profile k{tag}Profile = {{
        "{label} {'.'.join(map(str, version))}",
        0x{pack_version(*version):08x}u,
        0x{data['table_rva']:08x}u, 0x{data['head_rva']:08x}u, 0x{data['tail_rva']:08x}u, 0x{data['lock_rva']:08x}u,
        0x{data['lock_write_rva']:08x}u, 0x{data['unlock_write_rva']:08x}u,
        0x{data['stock_entries']:x}u, 0x{data['raised_entries']:x}u, 0x{data['entry_size']:x}u,
        0x{hooks['helper_rva']:08x}u, {{ {hb} }},
        k{tag}AssignmentHookSites, static_cast<uint32_t>(sizeof(k{tag}AssignmentHookSites) / sizeof(k{tag}AssignmentHookSites[0])),
        k{tag}Fields, static_cast<uint32_t>(sizeof(k{tag}Fields) / sizeof(k{tag}Fields[0])),
        k{tag}BytePatches, static_cast<uint32_t>(sizeof(k{tag}BytePatches) / sizeof(k{tag}BytePatches[0])),
        k{tag}TableRefs, static_cast<uint32_t>(sizeof(k{tag}TableRefs) / sizeof(k{tag}TableRefs[0])),
        k{tag}InitPatches, static_cast<uint32_t>(sizeof(k{tag}InitPatches) / sizeof(k{tag}InitPatches[0])),
        k{tag}ReleaseSites, static_cast<uint32_t>(sizeof(k{tag}ReleaseSites) / sizeof(k{tag}ReleaseSites[0])),
    }};""")
    return "\n".join(out)


def render(data: dict[str, dict]) -> str:
    enum_body = "\n".join(f"        kCat_{c} = {i}," for i, c in enumerate(CATS))
    names = "\n".join(f'            "{c}",' for c in CATS)

    parts = [HEADER % (enum_body, names)]
    for tag, label, version in RUNTIMES:
        parts.append(emit(tag, label, data[tag], version))
        parts.append("")
    profile_refs = ", ".join(f"&k{tag}Profile" for tag, _, _ in RUNTIMES)
    parts.append(f"""    inline const Profile* const kProfiles[] = {{ {profile_refs} }};
    inline constexpr uint32_t kProfileCount = sizeof(kProfiles) / sizeof(kProfiles[0]);
}}
""")
    return "\n".join(parts)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--se", required=True)
    ap.add_argument("--ae", required=True)
    ap.add_argument("--gog", required=True)
    ap.add_argument("--vr", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    data = {
        "SE": json.load(open(a.se)),
        "AE": json.load(open(a.ae)),
        "GOG": json.load(open(a.gog)),
        "VR": json.load(open(a.vr)),
    }
    text = render(data)
    with open(a.out, "w", newline="\n") as fh:
        fh.write(text)
    counts = ", ".join(
        f"{tag} {len(data[tag]['patches'])}+{len(data[tag]['raw_patches'])}+"
        f"{len(data[tag]['table_refs'])}" for tag, _, _ in RUNTIMES)
    print(f"wrote {a.out}: {counts}")


if __name__ == "__main__":
    main()
