"""Render the committed patch profiles as a human-readable instruction audit.

The JSON profiles remain the machine-readable source of truth.  This renderer
constructs the exact static replacement bytes using the same field/whole-byte
rules as the DLL, disassembles both sides, and emits one Markdown page per
runtime plus a small index.

Two signed 32-bit displacement families are necessarily runtime-dependent:
RIP-relative ``disp32`` references to the newly allocated handle table and
``rel32`` generation-diagnostic relay calls. Their invariant bytes are emitted
exactly, their four-byte displacements are shown as ``??``, and the document
gives the exact expression used at runtime.
"""

from __future__ import annotations

import argparse
import html
import json
import pathlib
import re
from collections.abc import Mapping, Sequence

from capstone import CS_ARCH_X86, CS_MODE_64, Cs


RUNTIME_SPECS = (
    ("SE", "Skyrim SE", "1.5.97.0", "SE-1.5.97.md"),
    ("AE", "Skyrim AE", "1.6.1170.0", "AE-1.6.1170.md"),
    ("GOG", "Skyrim GOG", "1.6.1179.0", "GOG-1.6.1179.md"),
    ("VR", "Skyrim VR", "1.4.15.0", "VR-1.4.15.md"),
)

_GENERATED_NOTICE = (
    "<!-- GENERATED by probes/gen_patch_docs.py; do not edit by hand. -->"
)

_SITE_ID_RE = re.compile(r'<a id="([a-z0-9-]+)"></a>')

_CATEGORY_DESCRIPTIONS = (
    ("index_mask", "Widen the table-entry/raw-handle index mask from 20 to 22 bits."),
    ("age_mask", "Move the unchanged six-bit generation field from bits 20–25 to 22–27."),
    ("age_inc_or_count", "Move the generation increment or entry-count constant by two bits."),
    ("table_bytes", "Increase the table byte extent from 16 MiB to 64 MiB."),
    ("clear_age", "Clear the relocated generation field while retaining the widened index."),
    ("clear_next", "Clear the widened next-index field."),
    ("clear_inuse", "Clear the relocated in-use bit."),
    ("inuse_bit", "Move an immediate in-use mask from bit 26 to bit 28."),
    ("inuse_bitpos", "Move a BT/BTS/BTR bit position from 26 to 28."),
    ("sidecar_read", "Read the complete 22-bit object index from the adjacent padding dword."),
    ("sidecar_write", "Publish the full sidecar index while preserving the legacy object word."),
    ("sidecar_release", "Clear the legacy object word and sidecar together."),
    ("table_relocation", "Retarget one RIP-relative table-address displacement."),
    ("init_guard", "Conditionally prevent stock initialization from overwriting the raised pool."),
    ("diagnostic_hook", "Optionally redirect a successful assignment CALL through the reuse relay."),
)


def _as_bytes(value: str, *, context: str) -> bytes:
    try:
        raw = bytes.fromhex(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{context}: invalid hexadecimal byte string") from exc
    if not raw:
        raise ValueError(f"{context}: empty instruction window")
    if len(raw) > 15:
        raise ValueError(f"{context}: x64 instruction window exceeds 15 bytes")
    return raw


def _instruction_lines(profile: Mapping, rva: int, raw: bytes, *, context: str) -> list[str]:
    md = Cs(CS_ARCH_X86, CS_MODE_64)
    address = int(profile["image_base"]) + rva
    instructions = list(md.disasm(raw, address))
    if not instructions or sum(ins.size for ins in instructions) != len(raw):
        raise ValueError(f"{context}: bytes do not decode as complete x64 instructions")
    expected_address = address
    lines: list[str] = []
    for ins in instructions:
        if ins.address != expected_address:
            raise ValueError(f"{context}: disassembly is not contiguous")
        expected_address += ins.size
        lines.append(f"{ins.mnemonic} {ins.op_str}".rstrip())
    return lines


def _validate_stored_asm(record: Mapping, lines: Sequence[str], *, context: str) -> None:
    stored = record.get("asm")
    if stored is not None and stored != "; ".join(lines):
        raise ValueError(
            f"{context}: stored disassembly differs from decoding the stored bytes")


def _field_replacement(profile: Mapping, record: Mapping, *, context: str) -> bytes:
    raw = bytearray(_as_bytes(record["orig"], context=context))
    length = int(record["len"])
    offset = int(record["field_off"])
    width = int(record["field_w"])
    if len(raw) != length or width not in (1, 4) or not (0 <= offset <= length - width):
        raise ValueError(f"{context}: invalid field bounds")
    mask = (1 << (width * 8)) - 1
    old_bytes = (int(record["old"]) & mask).to_bytes(width, "little")
    if raw[offset : offset + width] != old_bytes:
        raise ValueError(f"{context}: old field value does not match stock bytes")
    raw[offset : offset + width] = (
        int(record["new"]) & mask
    ).to_bytes(width, "little")
    return bytes(raw)


def _hex_bytes(raw: bytes) -> str:
    return " ".join(f"{value:02X}" for value in raw)


def _hex_template(raw: bytes, offset: int, width: int) -> str:
    if not (0 <= offset <= len(raw) - width):
        raise ValueError("dynamic displacement field lies outside its instruction")
    return " ".join(
        "??" if offset <= index < offset + width else f"{value:02X}"
        for index, value in enumerate(raw)
    )


def _escape(value: object) -> str:
    return html.escape(str(value), quote=False).replace("|", "&#124;").replace("\n", " ")


def _code(value: object) -> str:
    return f"<code>{_escape(value)}</code>"


def _instruction_cell(raw_text: str, lines: Sequence[str]) -> str:
    rendered = [_code(raw_text)]
    rendered.extend(_code(line) for line in lines)
    return "<br>".join(rendered)


def _site_cell(site_id: str, rva: int) -> str:
    return f'<a id="{site_id}"></a>{_code(f"0x{rva:08X}")}'


def _details(title: str, rows: Sequence[str]) -> str:
    body = [
        "<details>",
        f"<summary>{_escape(title)}</summary>",
        "",
        "| RVA | Len | Classification | Stock bytes / disassembly | Replacement bytes / disassembly | Notes |",
        "|---:|---:|---|---|---|---|",
        *rows,
        "",
        "</details>",
    ]
    return "\n".join(body)


def _simple_details(title: str, header: str, separator: str, rows: Sequence[str]) -> str:
    return "\n".join(
        ["<details>", f"<summary>{_escape(title)}</summary>", "", header, separator, *rows, "", "</details>"]
    )


def expected_record_ids(profile: Mapping) -> list[str]:
    """Return every explicit row id the runtime document must contain, in order."""
    groups = (
        ("field", profile["patches"], "rva"),
        ("byte", profile["raw_patches"], "rva"),
        ("table-ref", profile["table_refs"], "rva"),
        ("init", profile["init_patches"], "rva"),
        ("assignment-hook", profile["assignment_hooks"]["sites"], "call_rva"),
        ("release-alias", profile["release_sites"], "rva"),
        ("excluded-literal", profile.get("excluded_literals", []), "rva"),
        ("excluded-shift", profile.get("excluded_shift11", []), "rva"),
    )
    out = [
        f"{prefix}-{int(record[key]):08x}"
        for prefix, records, key in groups
        for record in sorted(records, key=lambda item: int(item[key]))
    ]
    out.extend(
        f"fingerprint-outside-{int(rva):08x}"
        for rva in sorted(profile.get("fingerprint_outside", []))
    )
    if len(out) != len(set(out)):
        raise ValueError("runtime profile produces duplicate documentation record ids")
    return out


def extract_record_ids(document: str) -> list[str]:
    """Extract the explicit row ids from one generated runtime document."""
    return _SITE_ID_RE.findall(document)


def _field_rows(profile: Mapping) -> list[str]:
    rows: list[str] = []
    for record in sorted(profile["patches"], key=lambda item: int(item["rva"])):
        rva = int(record["rva"])
        context = f"field patch at RVA 0x{rva:08X}"
        stock = _as_bytes(record["orig"], context=context)
        replacement = _field_replacement(profile, record, context=context)
        stock_lines = _instruction_lines(profile, rva, stock, context=context)
        replacement_lines = _instruction_lines(
            profile, rva, replacement, context=f"{context} replacement")
        _validate_stored_asm(record, stock_lines, context=context)
        rows.append(
            "| "
            + " | ".join(
                (
                    _site_cell(f"field-{rva:08x}", rva),
                    str(len(stock)),
                    _code(record["cat"]),
                    _instruction_cell(_hex_bytes(stock), stock_lines),
                    _instruction_cell(_hex_bytes(replacement), replacement_lines),
                    f"field +{int(record['field_off'])}, {int(record['field_w'])} byte(s)",
                )
            )
            + " |"
        )
    return rows


def _byte_rows(profile: Mapping) -> list[str]:
    rows: list[str] = []
    for record in sorted(profile["raw_patches"], key=lambda item: int(item["rva"])):
        rva = int(record["rva"])
        context = f"byte patch at RVA 0x{rva:08X}"
        stock = _as_bytes(record["orig"], context=context)
        replacement = _as_bytes(record["new"], context=f"{context} replacement")
        if len(stock) != int(record["len"]) or len(replacement) != len(stock):
            raise ValueError(f"{context}: stock/replacement lengths differ")
        stock_lines = _instruction_lines(profile, rva, stock, context=context)
        replacement_lines = _instruction_lines(
            profile, rva, replacement, context=f"{context} replacement")
        _validate_stored_asm(record, stock_lines, context=context)
        notes: list[str] = []
        if "mode" in record:
            notes.append(str(record["mode"]))
        if "sidecar_disp" in record:
            notes.append(f"sidecar +0x{int(record['sidecar_disp']):X}")
        if "clear_rva" in record:
            notes.append(f"clear RVA 0x{int(record['clear_rva']):08X}")
        rows.append(
            "| "
            + " | ".join(
                (
                    _site_cell(f"byte-{rva:08x}", rva),
                    str(len(stock)),
                    _code(record["cat"]),
                    _instruction_cell(_hex_bytes(stock), stock_lines),
                    _instruction_cell(_hex_bytes(replacement), replacement_lines),
                    _escape("; ".join(notes) if notes else "—"),
                )
            )
            + " |"
        )
    return rows


def _table_reference_rows(profile: Mapping) -> list[str]:
    rows: list[str] = []
    table_rva = int(profile["table_rva"])
    for record in sorted(profile["table_refs"], key=lambda item: int(item["rva"])):
        rva = int(record["rva"])
        context = f"table reference at RVA 0x{rva:08X}"
        stock = _as_bytes(record["orig"], context=context)
        length = int(record["len"])
        offset = int(record["disp_off"])
        if len(stock) != length or not (0 <= offset <= length - 4):
            raise ValueError(f"{context}: invalid RIP-relative disp32 bounds")
        displacement = int.from_bytes(stock[offset : offset + 4], "little", signed=True)
        if rva + length + displacement != table_rva:
            raise ValueError(f"{context}: stock disp32 does not resolve to the stock table")
        stock_lines = _instruction_lines(profile, rva, stock, context=context)
        _validate_stored_asm(record, stock_lines, context=context)
        if len(stock_lines) != 1 or not stock_lines[0].startswith("lea "):
            raise ValueError(f"{context}: expected one LEA instruction")
        destination = stock_lines[0][4:].split(",", 1)[0]
        replacement_lines = [f"lea {destination}, [allocated_handle_table]"]
        rows.append(
            "| "
            + " | ".join(
                (
                    _site_cell(f"table-ref-{rva:08x}", rva),
                    str(len(stock)),
                    _code("table_relocation"),
                    _instruction_cell(_hex_bytes(stock), stock_lines),
                    _instruction_cell(_hex_template(stock, offset, 4), replacement_lines),
                    _code("disp32(new_table) = tableVA - (moduleBase + RVA + len)"),
                )
            )
            + " |"
        )
    return rows


def _initializer_rows(profile: Mapping) -> list[str]:
    rows: list[str] = []
    for record in sorted(profile["init_patches"], key=lambda item: int(item["rva"])):
        rva = int(record["rva"])
        context = f"initializer guard at RVA 0x{rva:08X}"
        stock = _as_bytes(record["orig"], context=context)
        replacement = _as_bytes(record["new"], context=f"{context} replacement")
        if len(stock) != int(record["len"]) or len(replacement) != len(stock):
            raise ValueError(f"{context}: stock/replacement lengths differ")
        stock_lines = _instruction_lines(profile, rva, stock, context=context)
        replacement_lines = _instruction_lines(
            profile, rva, replacement, context=f"{context} replacement")
        rows.append(
            "| "
            + " | ".join(
                (
                    _site_cell(f"init-{rva:08x}", rva),
                    str(len(stock)),
                    _code(record["cat"]),
                    _instruction_cell(_hex_bytes(stock), stock_lines),
                    _instruction_cell(_hex_bytes(replacement), replacement_lines),
                    _escape(f"conditional: {record['asm']}"),
                )
            )
            + " |"
        )
    return rows


def _assignment_rows(profile: Mapping) -> list[str]:
    rows: list[str] = []
    hooks = profile["assignment_hooks"]
    helper_rva = int(hooks["helper_rva"])
    for record in sorted(hooks["sites"], key=lambda item: int(item["call_rva"])):
        rva = int(record["call_rva"])
        context = f"assignment hook at RVA 0x{rva:08X}"
        stock = _as_bytes(record["call_bytes"], context=context)
        if len(stock) != 5 or stock[0] != 0xE8:
            raise ValueError(f"{context}: stock site is not one rel32 CALL")
        displacement = int.from_bytes(stock[1:], "little", signed=True)
        if rva + 5 + displacement != helper_rva or int(record["call_target_rva"]) != helper_rva:
            raise ValueError(f"{context}: stock CALL does not resolve to the shared helper")
        stock_lines = _instruction_lines(profile, rva, stock, context=context)
        notes = (
            f"optional diagnostic; owner 0x{int(record['function_rva']):08X}; "
            f"writer 0x{int(record['writer_rva']):08X}; lock bracket "
            f"0x{int(record['lock_call_rva']):08X}–0x{int(record['unlock_call_rva']):08X}"
        )
        rows.append(
            "| "
            + " | ".join(
                (
                    _site_cell(f"assignment-hook-{rva:08x}", rva),
                    "5",
                    _code("diagnostic_hook"),
                    _instruction_cell(_hex_bytes(stock), stock_lines),
                    _instruction_cell("E8 ?? ?? ?? ??", ["call generation_wrap_relay"]),
                    _escape(notes) + "<br>" + _code("rel32(relay) = relayVA - (moduleBase + RVA + 5)"),
                )
            )
            + " |"
        )
    return rows


def _appendix(profile: Mapping) -> str:
    parts = [
        "## Audited non-patch records",
        "",
        "These rows are independent coverage evidence or explicit exclusions. They are not additional writes.",
        "",
    ]

    release_rows = []
    for record in sorted(profile["release_sites"], key=lambda item: int(item["rva"])):
        rva = int(record["rva"])
        raw_patch_rva = int(record["raw_patch_rva"])
        release_rows.append(
            "| "
            + " | ".join(
                (
                    _site_cell(f"release-alias-{rva:08x}", rva),
                    _code(record["orig"]),
                    _code(record["asm"]),
                    f"covered by {_code(f'byte-{raw_patch_rva:08x}')}; {_escape(record['policy'])}",
                )
            )
            + " |"
        )
    parts.append(
        _simple_details(
            f"Release-site census ({len(release_rows)})",
            "| Clear RVA | Stock bytes | Stock disassembly | Coverage |",
            "|---:|---|---|---|",
            release_rows,
        )
    )

    excluded_rows = []
    for record in sorted(profile.get("excluded_literals", []), key=lambda item: int(item["rva"])):
        rva = int(record["rva"])
        excluded_rows.append(
            "| "
            + " | ".join(
                (
                    _site_cell(f"excluded-literal-{rva:08x}", rva),
                    _code(record["cat"]),
                    _code(record["asm"]),
                    _escape(record["why"]),
                )
            )
            + " |"
        )
    for record in sorted(profile.get("excluded_shift11", []), key=lambda item: int(item["rva"])):
        rva = int(record["rva"])
        source = (
            f"source RVA 0x{int(record['source_rva']):08X}, +0x{int(record['source_disp']):X}"
            if "source_rva" in record and "source_disp" in record
            else "no classified source"
        )
        excluded_rows.append(
            "| "
            + " | ".join(
                (
                    _site_cell(f"excluded-shift-{rva:08x}", rva),
                    _code("excluded_shift11"),
                    _escape(source),
                    _escape(record["why"]),
                )
            )
            + " |"
        )
    for rva_value in profile.get("fingerprint_outside", []):
        rva = int(rva_value)
        excluded_rows.append(
            "| "
            + " | ".join(
                (
                    _site_cell(f"fingerprint-outside-{rva:08x}", rva),
                    _code("unresolved_age_mask_fingerprint"),
                    "—",
                    "generation should not ship with this record",
                )
            )
            + " |"
        )
    parts.extend(
        (
            "",
            _simple_details(
                f"Explicit exclusions ({len(excluded_rows)})",
                "| RVA | Classification | Source / disassembly | Reason |",
                "|---:|---|---|---|",
                excluded_rows,
            ),
        )
    )
    return "\n".join(parts)


def _render_runtime(tag: str, label: str, version: str, filename: str, profile: Mapping) -> str:
    if profile.get("runtime") != tag:
        raise ValueError(f"{tag}: profile runtime tag is {profile.get('runtime')!r}")
    fields = _field_rows(profile)
    byte_patches = _byte_rows(profile)
    table_refs = _table_reference_rows(profile)
    init_patches = _initializer_rows(profile)
    assignment_hooks = _assignment_rows(profile)
    core_count = len(fields) + len(byte_patches) + len(table_refs) + len(init_patches)
    hooks = profile["assignment_hooks"]
    image_base = _code(f"0x{int(profile['image_base']):X}")
    table_rva = _code(f"0x{int(profile['table_rva']):08X}")
    head_rva = _code(f"0x{int(profile['head_rva']):08X}")
    tail_rva = _code(f"0x{int(profile['tail_rva']):08X}")
    lock_rva = _code(f"0x{int(profile['lock_rva']):08X}")
    helper_rva = _code(f"0x{int(hooks['helper_rva']):08X}")

    parts = [
        _GENERATED_NOTICE,
        f"# {label} {version} patch-site audit",
        "",
        "[Back to the generated audit index](README.md)",
        "",
        "This page is a deterministic projection of "
        f"[`artifacts/patch_{tag}.json`](../../artifacts/patch_{tag}.json). "
        "Every executable mutation record appears exactly once below.",
        "",
        "| Profile fact | Value |",
        "|---|---|",
        f"| Runtime tag | {_code(tag)} |",
        f"| Executable SHA-256 | {_code(profile['exe_sha256'])} |",
        f"| Executable size | {int(profile['exe_size']):,} bytes |",
        f"| Image base | {image_base} |",
        f"| Stock table RVA | {table_rva} |",
        f"| Head / tail / lock RVAs | {head_rva} / {tail_rva} / {lock_rva} |",
        f"| Core mutation records | {core_count:,} |",
        f"| Optional diagnostic redirects | {len(assignment_hooks)} |",
        "",
        "## How to read dynamic replacements",
        "",
        "Static field, sidecar, and initializer replacements show every byte exactly. "
        "The table address and diagnostic relay address are selected at runtime, so the "
        "four-byte RIP-relative `disp32` table fields and `rel32` CALL fields cannot be "
        "fixed in a launch-independent file. Those bytes are shown as `??`; the invariant "
        "opcode bytes, symbolic disassembly, and exact displacement expression are shown "
        "alongside them.",
        "",
        "## Core cap transaction",
        "",
        _details(f"Field rewrites ({len(fields)})", fields),
        "",
        _details(f"Whole-window sidecar rewrites ({len(byte_patches)})", byte_patches),
        "",
        _details(f"RIP-relative table disp32 rewrites ({len(table_refs)})", table_refs),
        "",
        _details(f"Conditional initializer guards ({len(init_patches)})", init_patches),
        "",
        "## Optional generation-wrap diagnostic",
        "",
        f"The shared stock assignment helper is fingerprinted at RVA {helper_rva} "
        f"with bytes {_code(_hex_bytes(bytes.fromhex(hooks['helper_bytes'])))}. "
        "The helper is not overwritten; each call below is redirected to an allocated relay "
        "only when generation-wrap detection is enabled and all fingerprints verify.",
        "",
        _details(f"Assignment-call redirects ({len(assignment_hooks)})", assignment_hooks),
        "",
        _appendix(profile),
        "",
    ]
    rendered = "\n".join(parts)
    actual_ids = extract_record_ids(rendered)
    wanted_ids = expected_record_ids(profile)
    if actual_ids != wanted_ids:
        missing = sorted(set(wanted_ids) - set(actual_ids))
        extra = sorted(set(actual_ids) - set(wanted_ids))
        raise ValueError(
            f"{tag}: documentation record coverage differs "
            f"(missing={missing[:3]}, extra={extra[:3]})")
    if not filename.endswith(".md"):
        raise ValueError(f"{tag}: runtime documentation filename is not Markdown")
    return rendered


def _render_index(profiles: Mapping[str, Mapping]) -> str:
    rows = []
    core_total = 0
    hook_total = 0
    used_categories = {"table_relocation", "diagnostic_hook"}
    for tag, label, version, filename in RUNTIME_SPECS:
        profile = profiles[tag]
        used_categories.update(record["cat"] for record in profile["patches"])
        used_categories.update(record["cat"] for record in profile["raw_patches"])
        used_categories.update(record["cat"] for record in profile["init_patches"])
        fields = len(profile["patches"])
        byte_patches = len(profile["raw_patches"])
        table_refs = len(profile["table_refs"])
        init_patches = len(profile["init_patches"])
        core = fields + byte_patches + table_refs + init_patches
        hooks = len(profile["assignment_hooks"]["sites"])
        core_total += core
        hook_total += hooks
        rows.append(
            f"| [{label} {version}]({filename}) | {fields} | {byte_patches} | "
            f"{table_refs} | {init_patches} | **{core}** | {hooks} |"
        )
    documented_categories = {category for category, _ in _CATEGORY_DESCRIPTIONS}
    if used_categories != documented_categories:
        raise ValueError(
            "patch-document category legend differs from the generated profile categories: "
            f"used={sorted(used_categories)}, documented={sorted(documented_categories)}")
    return "\n".join(
        (
            _GENERATED_NOTICE,
            "# Generated patch-site audit",
            "",
            "This directory is the human-readable rendering of the four maintained "
            "`artifacts/patch_*.json` profiles. It contains every cap-raise executable "
            "mutation record and every optional generation-wrap call redirect, with stock "
            "and replacement bytes and disassembly shown side by side.",
            "",
            "| Runtime | Field rewrites | Sidecar windows | Table refs | Init guards | Core sites | Optional redirects |",
            "|---|---:|---:|---:|---:|---:|---:|",
            *rows,
            f"| **Total** | | | | | **{core_total:,}** | **{hook_total}** |",
            "",
            "## Reading the audit",
            "",
            "Each runtime is split into the four core mutation mechanisms and the separate, "
            "fail-soft diagnostic hook. RVA, byte length, internal classification, complete "
            "stock bytes/disassembly, and replacement bytes/disassembly are recorded for "
            "every site. Release aliases and explicit false-positive exclusions appear in "
            "a non-patch appendix.",
            "",
            "A static document cannot contain launch-specific displacement bytes. Table "
            "references target a dynamically allocated 64 MiB table, and diagnostic calls "
            "target an allocated relay page. The table's RIP-relative `disp32` fields and "
            "the calls' `rel32` fields are shown as `?? ?? ?? ??`, together with the exact "
            "formula used to produce them. Every other replacement byte is exact.",
            "",
            "## Classification legend",
            "",
            "| Classification | Meaning |",
            "|---|---|",
            *(f"| {_code(category)} | {_escape(description)} |"
              for category, description in _CATEGORY_DESCRIPTIONS),
            "",
            "## Regeneration",
            "",
            "Run from the `Skyrim/` project directory after regenerating or reviewing the JSON profiles:",
            "",
            "```powershell",
            "python probes\\gen_patch_docs.py --se artifacts\\patch_SE.json --ae artifacts\\patch_AE.json --gog artifacts\\patch_GOG.json --vr artifacts\\patch_VR.json --out-dir docs\\patch-sites",
            "python probes\\verify_deliverable.py --offline",
            "```",
            "",
            "The verifier renders these files again in memory, requires byte-for-byte equality, "
            "and independently derives every documented mutation/evidence record ID from the "
            "exact JSON schema, requiring each one exactly once.",
            "",
        )
    )


def render_all(profiles: Mapping[str, Mapping]) -> dict[str, str]:
    """Return every generated document keyed by path relative to the output directory."""
    expected_tags = {tag for tag, *_ in RUNTIME_SPECS}
    if set(profiles) != expected_tags:
        raise ValueError(
            f"patch-document profiles are {sorted(profiles)}, expected {sorted(expected_tags)}")
    documents = {"README.md": _render_index(profiles)}
    for tag, label, version, filename in RUNTIME_SPECS:
        documents[filename] = _render_runtime(
            tag, label, version, filename, profiles[tag])
    return documents


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--se", required=True)
    parser.add_argument("--ae", required=True)
    parser.add_argument("--gog", required=True)
    parser.add_argument("--vr", required=True)
    parser.add_argument("--out-dir", required=True)
    args = parser.parse_args()

    profiles = {
        "SE": json.loads(pathlib.Path(args.se).read_text(encoding="utf-8")),
        "AE": json.loads(pathlib.Path(args.ae).read_text(encoding="utf-8")),
        "GOG": json.loads(pathlib.Path(args.gog).read_text(encoding="utf-8")),
        "VR": json.loads(pathlib.Path(args.vr).read_text(encoding="utf-8")),
    }
    documents = render_all(profiles)
    output_dir = pathlib.Path(args.out_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    for relative, text in documents.items():
        destination = output_dir / relative
        with destination.open("w", encoding="utf-8", newline="\n") as stream:
            stream.write(text)
    print(
        f"wrote {len(documents)} patch-audit documents to {output_dir}: "
        + ", ".join(documents)
    )


if __name__ == "__main__":
    main()
